services:
  api:
    build:
      context: ./guia2-vision-ia-api
      dockerfile: Dockerfile
    container_name: guia2-vision-ia-api
    ports:
      - "8006:8000"
    volumes:
      - ./guia2-vision-ia-api/app/output:/app/app/output
    restart: unless-stopped
    networks:
      - guia2-ia-network

  web:
    build:
      context: ./guia2-vision-ia-web
      dockerfile: Dockerfile
    container_name: guia2-vision-ia-frontend
    ports:
      - "8007:80" 
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - guia2-ia-network

networks:
  guia2-ia-network:
    driver: bridge